In [2]:
import json
import torch
import torch.nn as nn

In [24]:

a=torch.zeros((140454,60,5))

In [46]:
embeds = nn.Embedding(15479, 5)



In [62]:
print(embeds(torch.LongTensor([15478])))

tensor([[-0.0444,  1.8211, -0.9916, -0.5268,  1.1566]],
       grad_fn=<EmbeddingBackward0>)


In [22]:
max=0
with open('Dataset/Dataset.jsonl','r') as f:
        for line in f:
            data=json.loads(line)
            temp=len(data['Phrase'].split(' '))
            if temp>max:
                max=temp;
print(max)

52


In [9]:
total,correct=0,0
a=torch.tensor([[0],[1],[0]])
b=torch.tensor([[1],[0],[0]])
total += a.size(0)
correct += (a == b).sum()
1.0*correct/total

tensor(0.3333)

In [7]:
a=torch.tensor([[0,1,0,0,0],[1,0,0,0,0]]);
b=torch.tensor([1,0,0,0,0]);

print(a)
a.squeeze(1)
print(a)

tensor([[0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])
tensor([[0, 1, 0, 0, 0],
        [1, 0, 0, 0, 0]])


In [6]:
x=torch.tensor([[1,2,3],[4,5,6]])
print(x)
x, _ =x
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
